#!/bin/sh
set -eu

protected_ref="refs/heads/master"

while read local_ref local_sha remote_ref remote_sha
do
  if [ "$local_ref" = "$protected_ref" ] || [ "$remote_ref" = "$protected_ref" ]; then
    if [ "${ALLOW_MASTER_PUSH:-}" != "1" ]; then
      cat >&2 <<'MSG'
Blocked: master is SullyOS production.

Remix work must be pushed to sullyos-remix:
  https://sullyos-remix.sullyos-5fy.pages.dev/

If the user explicitly asked to promote to production, rerun the push with:
  ALLOW_MASTER_PUSH=1 git push origin master
MSG
      exit 1
    fi
  fi
done
